# Generated by Django 3.1.1 on 2021-03-26 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Slider1',
            fields=[
                ('pid', models.AutoField(primary_key=True, serialize=False)),
                ('image1', models.ImageField(default='', upload_to='images/')),
            ],
        ),
    ]
