# Generated by Django 3.1.1 on 2021-03-26 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0002_auto_20210326_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event_template',
            name='end_time',
            field=models.CharField(default='', max_length=16),
        ),
        migrations.AlterField(
            model_name='event_template',
            name='location',
            field=models.CharField(default='', max_length=26),
        ),
        migrations.AlterField(
            model_name='event_template',
            name='start_time',
            field=models.CharField(default='', max_length=16),
        ),
    ]
