# Generated by Django 3.1.1 on 2021-03-26 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0003_auto_20210326_1405'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event_template',
            old_name='details',
            new_name='name',
        ),
    ]
