# Generated by Django 3.1.1 on 2021-03-26 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0004_auto_20210326_1409'),
    ]

    operations = [
        migrations.CreateModel(
            name='like_template',
            fields=[
                ('pid', models.AutoField(primary_key=True, serialize=False)),
                ('day', models.CharField(default='', max_length=6)),
                ('month', models.CharField(default='', max_length=16)),
                ('start_time', models.CharField(default='', max_length=16)),
                ('end_time', models.CharField(default='', max_length=16)),
                ('location', models.CharField(default='', max_length=26)),
                ('name', models.CharField(default='', max_length=100)),
                ('image1', models.ImageField(default='', upload_to='images/')),
            ],
        ),
    ]
