# Generated by Django 3.1.1 on 2021-03-26 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0005_like_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='like_template',
            name='ids',
            field=models.CharField(default='', max_length=6),
        ),
    ]
